# Copyright 2026 Observational Health Data Sciences and Informatics
#
# This file is part of Medusa
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Run Instrument Validation Diagnostics
#'
#' @title Instrument diagnostics for MR analysis
#'
#' @description
#' Performs comprehensive instrument validation using OMOP covariate data. This
#' is a key differentiating feature of the Medusa package. Diagnostics include
#' first-stage F-statistics, instrument PheWAS across OMOP covariate domains,
#' negative control outcome tests, allele frequency comparisons, and genotype
#' missingness summaries.
#'
#' The results feed directly into the HTML report generated by
#' \code{\link{generateMRReport}}.
#'
#' @param cohortData Data frame. Output of \code{\link{buildMRCohort}}.
#' @param covariateData List. Output of \code{\link{buildMRCovariates}}.
#' @param instrumentTable Data frame. Output of \code{\link{getMRInstruments}}.
#' @param exposureProxyConceptIds Optional integer vector of OMOP concept IDs
#'   for an exposure measurement proxy (e.g., IL-6 lab measurement). Used
#'   to compute first-stage F-statistic from actual data rather than GWAS
#'   approximation.
#' @param negativeControlOutcomeIds Optional integer vector of cohort IDs for
#'   negative control outcomes. If NULL, uses package default set.
#' @param pValueThreshold Numeric. P-value threshold for PheWAS significance.
#'   Default is Bonferroni-corrected (0.05 / number of covariates tested).
#'
#' @return A named list with class "medusaDiagnostics" containing:
#'   \describe{
#'     \item{fStatistics}{Data frame with snp_id, fStatistic, and weakFlag.}
#'     \item{phewasResults}{Data frame with snp_id, covariate_id, covariate_name,
#'       beta, se, pval, domain_id, significant.}
#'     \item{negativeControlResults}{Data frame with snp_id, outcome_id, beta,
#'       se, pval, or NULL if no negative controls provided. Note: negative
#'       control testing is not yet implemented; this slot currently returns
#'       an empty data frame when negative control IDs are supplied.}
#'     \item{afComparison}{Data frame with snp_id, eaf_gwas, eaf_cohort,
#'       eaf_diff, discrepancyFlag.}
#'     \item{missingnessReport}{Data frame with snp_id, n_total, n_missing,
#'       pct_missing, highMissingFlag.}
#'     \item{diagnosticFlags}{Named logical vector summarizing which checks
#'       raised concerns.}
#'   }
#'
#' @details
#' \strong{F-statistic}: If \code{exposureProxyConceptIds} are provided, the
#' first-stage F-statistic is computed by regressing the proxy measurement
#' on each SNP. Otherwise, the GWAS approximation (beta_ZX / se_ZX)^2 is used.
#' F < 10 indicates a potentially weak instrument.
#'
#' \strong{PheWAS}: Each SNP is regressed against every covariate in the
#' covariate matrix using logistic (binary) or linear (continuous) regression.
#' Bonferroni correction is applied. Significant associations may indicate
#' pleiotropy.
#'
#' \strong{Allele frequency check}: Compares the effect allele frequency in
#' the cohort to the GWAS reference. A discrepancy > 0.1 may indicate strand
#' flip or population mismatch.
#'
#' @references
#' Bowden, J., et al. (2018). Improving the accuracy of two-sample summary-data
#' Mendelian randomization: moving beyond the NOME assumption.
#' \emph{International Journal of Epidemiology}, 48(3), 728-742.
#'
#' @examples
#' # Using simulated data
#' simData <- simulateMRData(n = 1000, nSnps = 5)
#' covData <- simulateCovariateData(n = 1000, nCovariates = 20)
#'
#' @seealso \code{\link{buildMRCohort}}, \code{\link{buildMRCovariates}},
#'   \code{\link{generateMRReport}}
#'
#' @export
runInstrumentDiagnostics <- function(cohortData,
                                     covariateData,
                                     instrumentTable,
                                     exposureProxyConceptIds = NULL,
                                     negativeControlOutcomeIds = NULL,
                                     pValueThreshold = NULL) {
  # Input validation
  checkmate::assertDataFrame(cohortData, min.rows = 1)
  validateInstrumentTable(instrumentTable)

  snpCols <- grep("^snp_", names(cohortData), value = TRUE)
  if (length(snpCols) == 0) {
    stop("No SNP columns (snp_*) found in cohortData. Run buildMRCohort() first.")
  }

  nSnps <- nrow(instrumentTable)
  message(sprintf("Running instrument diagnostics for %d SNPs...", nSnps))

  # --- 1. F-statistics ---
  message("  Computing F-statistics...")
  fStatistics <- computeFStatistics(cohortData, instrumentTable,
                                     exposureProxyConceptIds)

  # --- 2. Instrument PheWAS ---
  message("  Running instrument PheWAS...")
  phewasResults <- runInstrumentPheWAS(cohortData, covariateData,
                                        instrumentTable, pValueThreshold)

  # --- 3. Negative control outcome test ---
  negativeControlResults <- NULL
  if (!is.null(negativeControlOutcomeIds)) {
    message("  Testing negative control outcomes...")
    negativeControlResults <- testNegativeControls(
      cohortData, instrumentTable, negativeControlOutcomeIds
    )
  }

  # --- 4. Allele frequency check ---
  message("  Comparing allele frequencies...")
  afComparison <- compareAlleleFrequencies(cohortData, instrumentTable)

  # --- 5. Missingness report ---
  message("  Summarizing genotype missingness...")
  missingnessReport <- summarizeGenotypeMissingness(cohortData, instrumentTable)

  # --- Assemble diagnostic flags ---
  diagnosticFlags <- c(
    weakInstruments = any(fStatistics$fStatistic < 10, na.rm = TRUE),
    phewasSignificant = any(phewasResults$significant, na.rm = TRUE),
    negativeControlFailure = !is.null(negativeControlResults) &&
      any(negativeControlResults$pval < 0.05, na.rm = TRUE),
    alleleFreqDiscrepancy = any(afComparison$discrepancyFlag, na.rm = TRUE),
    highMissingness = any(missingnessReport$highMissingFlag, na.rm = TRUE)
  )

  if (any(diagnosticFlags)) {
    flaggedChecks <- names(diagnosticFlags)[diagnosticFlags]
    warning(sprintf(
      "Instrument diagnostics flagged potential issues: %s. Review diagnostic report before proceeding.",
      paste(flaggedChecks, collapse = ", ")
    ))
  }

  result <- list(
    fStatistics = fStatistics,
    phewasResults = phewasResults,
    negativeControlResults = negativeControlResults,
    afComparison = afComparison,
    missingnessReport = missingnessReport,
    diagnosticFlags = diagnosticFlags
  )
  class(result) <- "medusaDiagnostics"

  message("Instrument diagnostics complete.")
  result
}


#' @keywords internal
computeFStatistics <- function(cohortData, instrumentTable,
                               exposureProxyConceptIds = NULL) {
  snpCols <- grep("^snp_", names(cohortData), value = TRUE)
  fStats <- data.frame(
    snp_id = instrumentTable$snp_id,
    fStatistic = NA_real_,
    source = NA_character_,
    weakFlag = NA,
    stringsAsFactors = FALSE
  )

  if (!is.null(exposureProxyConceptIds) && "exposure" %in% names(cohortData)) {
    # Compute from actual data
    for (i in seq_len(nrow(instrumentTable))) {
      snpCol <- snpCols[i]
      if (snpCol %in% names(cohortData)) {
        validIdx <- !is.na(cohortData[[snpCol]]) & !is.na(cohortData$exposure)
        if (sum(validIdx) > 10) {
          fit <- lm(cohortData$exposure[validIdx] ~ cohortData[[snpCol]][validIdx])
          fVal <- summary(fit)$fstatistic[1]
          fStats$fStatistic[i] <- unname(fVal)
          fStats$source[i] <- "cohort_data"
        }
      }
    }
  }

  # Fill in GWAS approximation for any missing
  missingF <- is.na(fStats$fStatistic)
  if (any(missingF)) {
    fStats$fStatistic[missingF] <- computeApproxFStatistic(
      instrumentTable$beta_ZX[missingF],
      instrumentTable$se_ZX[missingF]
    )
    fStats$source[missingF] <- "gwas_approximation"
  }

  fStats$weakFlag <- fStats$fStatistic < 10
  fStats
}


#' @keywords internal
runInstrumentPheWAS <- function(cohortData, covariateData, instrumentTable,
                                 pValueThreshold = NULL) {
  snpCols <- grep("^snp_", names(cohortData), value = TRUE)

  # Get covariates as a data frame
  if (inherits(covariateData, "medusaCovariateData")) {
    # Extract from FeatureExtraction object
    covDf <- as.data.frame(covariateData$covariateData$covariates)
    covRef <- as.data.frame(covariateData$covariateData$covariateRef)
  } else if (is.data.frame(covariateData)) {
    covDf <- covariateData
    covariateCols <- setdiff(names(covDf), "person_id")
    covRef <- data.frame(
      covariateId = seq_along(covariateCols),
      covariateName = covariateCols,
      domainId = "Unknown",
      stringsAsFactors = FALSE
    )
  } else {
    covDf <- covariateData
    covRef <- data.frame(covariateId = integer(0),
                          covariateName = character(0),
                          domainId = character(0),
                          stringsAsFactors = FALSE)
  }

  if (is.data.frame(covDf)) {
    covariateCols <- setdiff(names(covDf), c("person_id", "personId", "rowId"))
  } else {
    covariateCols <- character(0)
  }

  nTests <- length(snpCols) * length(covariateCols)
  if (is.null(pValueThreshold)) {
    pValueThreshold <- if (nTests > 0) 0.05 / nTests else 0.05
  }

  results <- data.frame(
    snp_id = character(0),
    covariate_name = character(0),
    beta = numeric(0),
    se = numeric(0),
    pval = numeric(0),
    significant = logical(0),
    stringsAsFactors = FALSE
  )

  if (length(covariateCols) == 0 || length(snpCols) == 0) {
    return(results)
  }

  # Merge cohort data with covariates if needed
  if ("personId" %in% names(covDf)) {
    mergedData <- dplyr::left_join(cohortData, covDf, by = "personId")
  } else if ("person_id" %in% names(covDf)) {
    mergedData <- dplyr::left_join(
      cohortData, covDf,
      by = c("personId" = "person_id")
    )
  } else {
    mergedData <- cohortData
  }

  for (snpCol in snpCols) {
    for (covCol in covariateCols) {
      validIdx <- !is.na(mergedData[[snpCol]]) & !is.na(mergedData[[covCol]])
      if (sum(validIdx) < 20) next

      y <- mergedData[[covCol]][validIdx]
      x <- mergedData[[snpCol]][validIdx]

      tryCatch({
        isBinary <- all(y %in% c(0, 1))
        if (isBinary) {
          if (length(unique(y)) < 2) next
          fit <- glm(y ~ x, family = binomial())
        } else {
          fit <- lm(y ~ x)
        }
        coefs <- summary(fit)$coefficients
        if (nrow(coefs) >= 2) {
          results <- rbind(results, data.frame(
            snp_id = sub("^snp_", "", snpCol),
            covariate_name = covCol,
            beta = coefs[2, 1],
            se = coefs[2, 2],
            pval = coefs[2, 4],
            significant = coefs[2, 4] < pValueThreshold,
            stringsAsFactors = FALSE
          ))
        }
      }, error = function(e) NULL)
    }
  }

  nTested <- nrow(results)
  nSkipped <- nTests - nTested
  message(sprintf("  PheWAS: tested %d of %d SNP-covariate pairs (%d skipped due to low N or no variation).",
                  nTested, nTests, nSkipped))

  results
}


#' @keywords internal
testNegativeControls <- function(cohortData, instrumentTable,
                                  negativeControlOutcomeIds) {
  message("  Negative control outcome testing is not yet implemented. ",
          "The negativeControlFailure diagnostic flag will be FALSE.")
  data.frame(
    snp_id = character(0),
    outcome_id = integer(0),
    beta = numeric(0),
    se = numeric(0),
    pval = numeric(0),
    stringsAsFactors = FALSE
  )
}


#' @keywords internal
compareAlleleFrequencies <- function(cohortData, instrumentTable) {
  snpCols <- grep("^snp_", names(cohortData), value = TRUE)

  afComparison <- data.frame(
    snp_id = instrumentTable$snp_id,
    eaf_gwas = instrumentTable$eaf,
    eaf_cohort = NA_real_,
    eaf_diff = NA_real_,
    discrepancyFlag = NA,
    stringsAsFactors = FALSE
  )

  for (i in seq_len(nrow(instrumentTable))) {
    snpCol <- makeSnpColumnName(instrumentTable$snp_id[i])
    if (snpCol %in% names(cohortData)) {
      genotypes <- cohortData[[snpCol]]
      validGeno <- genotypes[!is.na(genotypes)]
      if (length(validGeno) > 0) {
        eafCohort <- mean(validGeno) / 2
        afComparison$eaf_cohort[i] <- eafCohort
        afComparison$eaf_diff[i] <- abs(eafCohort - instrumentTable$eaf[i])
        afComparison$discrepancyFlag[i] <- afComparison$eaf_diff[i] > 0.1
      }
    }
  }

  afComparison
}


#' @keywords internal
summarizeGenotypeMissingness <- function(cohortData, instrumentTable) {
  snpCols <- grep("^snp_", names(cohortData), value = TRUE)
  nTotal <- nrow(cohortData)

  missingnessReport <- data.frame(
    snp_id = instrumentTable$snp_id,
    n_total = nTotal,
    n_missing = NA_integer_,
    pct_missing = NA_real_,
    highMissingFlag = NA,
    stringsAsFactors = FALSE
  )

  for (i in seq_len(nrow(instrumentTable))) {
    snpCol <- makeSnpColumnName(instrumentTable$snp_id[i])
    if (snpCol %in% names(cohortData)) {
      nMissing <- sum(is.na(cohortData[[snpCol]]))
      missingnessReport$n_missing[i] <- nMissing
      missingnessReport$pct_missing[i] <- 100 * nMissing / nTotal
      missingnessReport$highMissingFlag[i] <- (nMissing / nTotal) > 0.10
    }
  }

  missingnessReport
}
